### ISSUE TITLE
Suggestion to include IMSLP permalink (minimal improvement)

### ISSUE THREAD

**Issue by johentsch** [craigsapp/bach-370-chorales#6]
As sugar for the user you could replace the IMSLP link in the README with this permalink that unequivocally identifies the edition without the need to search for Plate V.A. 10 https://imslp.org/wiki/Special:ReverseLookup/495149

**Comment by johentsch** [comment]
Thanks! :+1:

**Comment by craigsapp** [comment]
Thanks! Added in commit https://github.com/craigsapp/bach-370-chorales/commit/99728b97c54735e491d6574d10ada4ddf0d003e6

I notice that the link resolves to https://imslp.org/wiki/371_Vierstimmige_Choralges%C3%A4nge_(Bach,_Johann_Sebastian)#IMSLP495149

Where `#IMSLP495149` is the anchor tag to scroll to that specific edition on the page.

Since the original print is available online (and I have also since acquired a copy of the original edition printed directly from those plates), I will probably omit the reprint info in the README as well (and make notes in the score related to any corrections made in reprints when they are found).

For the first 50 chorales, I created separate PDF files for each chorale (but then got bored of creating the PDF file for the rest).  So for some chorales, you can view the source edition (reprint) from VHV:

<img width="1789" alt="Screenshot 2023-06-20 at 8 44 42 AM" src="https://github.com/craigsapp/bach-370-chorales/assets/3487289/b7170e57-aa1f-4272-a91e-7a85a3a40044">

Keyboard shortcut is alt-p, or click on the PDF icon under the "er" in "Herzens" of the top title.
